# Generated by Django 5.0.3 on 2024-04-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bodypart_trainingmenu_trainingrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingmenu',
            old_name='bodyPart',
            new_name='body_part',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.trainingsession'),
        ),
    ]
