# Generated by Django 5.0.3 on 2024-04-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bodypart_trainingmenu_body_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrecord',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='weight',
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.trainingmenu'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.trainingsession'),
        ),
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.trainingrecord')),
            ],
        ),
    ]
