# Generated by Django 5.0.3 on 2024-04-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_trainingrecord_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
