# Generated by Django 5.0.3 on 2024-04-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_menu_trainingrecord_menuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingrecord',
            old_name='menuId',
            new_name='menu',
        ),
    ]
