# Generated by Django 5.0.3 on 2024-04-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trainingrecord_body_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.trainingmenu'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.trainingsession'),
        ),
    ]
