# Generated by Django 5.0.3 on 2024-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_dateofbirth_profile_gender_profile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
