# Generated by Django 5.0.3 on 2024-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_trainingrecord_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
